services:

  db:
    image: postgres:18-alpine
    env_file:
      - env/db.env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql
    restart: unless-stopped
