services:

  db:
    image: postgres:18-alpine
    env_file:
      - docker/db.env
    ports:
      - "5432:5432"
    volumes:
      - ./docker/.data/db:/var/lib/postgresql
    restart: unless-stopped

  azimuth:
    image: ghcr.io/roman-dynin/azimuth:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
